name: Compile

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with AHK v2
        uses: nukdokplex/autohotkey-build@v1
        with:
          version: v2.0.2
          x64: true
          x64_suffix: ""
          compression: upx
          in: ""
          out: build
      - name: Do Something with builded scripts
        shell: pwsh
        run: |
          ls build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/EhAria2.exe
            build/EhAria2Extension.exe
            build/EhAria2Torrent.exe
            build/EhAria2Manager.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
